### ISSUE TITLE
use wifi to control servo

### ISSUE THREAD

**Issue by gaodianzhuo** [khoih-prog/ESP32_C3_ISR_Servo#1]
amazing job.Could you write an instance of wifi working with this library?

**Comment by khoih-prog** [comment]
Sorry I have no time to do this and leave it as a **simple exercise** for you to do. If you still can't do it, post on a **Forum** to ask for help.

I'm closing the issue because this has nothing to do with the library. Next time, post on the `Discussions` if the topic is not an issue of the library.

Good Luck,
